// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: cap/cap.proto

package cap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PenseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pense      string `protobuf:"bytes,1,opt,name=pense,proto3" json:"pense,omitempty"`
	PenseIndex string `protobuf:"bytes,2,opt,name=penseIndex,proto3" json:"penseIndex,omitempty"`
}

func (x *PenseRequest) Reset() {
	*x = PenseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cap_cap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PenseRequest) ProtoMessage() {}

func (x *PenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cap_cap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PenseRequest.ProtoReflect.Descriptor instead.
func (*PenseRequest) Descriptor() ([]byte, []int) {
	return file_cap_cap_proto_rawDescGZIP(), []int{0}
}

func (x *PenseRequest) GetPense() string {
	if x != nil {
		return x.Pense
	}
	return ""
}

func (x *PenseRequest) GetPenseIndex() string {
	if x != nil {
		return x.PenseIndex
	}
	return ""
}

type PenseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pense string `protobuf:"bytes,1,opt,name=pense,proto3" json:"pense,omitempty"`
}

func (x *PenseReply) Reset() {
	*x = PenseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cap_cap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PenseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PenseReply) ProtoMessage() {}

func (x *PenseReply) ProtoReflect() protoreflect.Message {
	mi := &file_cap_cap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PenseReply.ProtoReflect.Descriptor instead.
func (*PenseReply) Descriptor() ([]byte, []int) {
	return file_cap_cap_proto_rawDescGZIP(), []int{1}
}

func (x *PenseReply) GetPense() string {
	if x != nil {
		return x.Pense
	}
	return ""
}

var File_cap_cap_proto protoreflect.FileDescriptor

var file_cap_cap_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x61, 0x70, 0x2f, 0x63, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x63, 0x61, 0x70, 0x22, 0x44, 0x0a, 0x0c, 0x50, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65,
	0x6e, 0x73, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x65, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x22, 0x0a, 0x0a, 0x50, 0x65,
	0x6e, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x32, 0x34,
	0x0a, 0x03, 0x43, 0x61, 0x70, 0x12, 0x2d, 0x0a, 0x05, 0x50, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x11,
	0x2e, 0x63, 0x61, 0x70, 0x2e, 0x50, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0f, 0x2e, 0x63, 0x61, 0x70, 0x2e, 0x50, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x72, 0x6a, 0x72, 0x69, 0x65, 0x6b, 0x65, 0x2f, 0x63, 0x61, 0x70, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cap_cap_proto_rawDescOnce sync.Once
	file_cap_cap_proto_rawDescData = file_cap_cap_proto_rawDesc
)

func file_cap_cap_proto_rawDescGZIP() []byte {
	file_cap_cap_proto_rawDescOnce.Do(func() {
		file_cap_cap_proto_rawDescData = protoimpl.X.CompressGZIP(file_cap_cap_proto_rawDescData)
	})
	return file_cap_cap_proto_rawDescData
}

var file_cap_cap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cap_cap_proto_goTypes = []interface{}{
	(*PenseRequest)(nil), // 0: cap.PenseRequest
	(*PenseReply)(nil),   // 1: cap.PenseReply
}
var file_cap_cap_proto_depIdxs = []int32{
	0, // 0: cap.Cap.Pense:input_type -> cap.PenseRequest
	1, // 1: cap.Cap.Pense:output_type -> cap.PenseReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cap_cap_proto_init() }
func file_cap_cap_proto_init() {
	if File_cap_cap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cap_cap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PenseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cap_cap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PenseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cap_cap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cap_cap_proto_goTypes,
		DependencyIndexes: file_cap_cap_proto_depIdxs,
		MessageInfos:      file_cap_cap_proto_msgTypes,
	}.Build()
	File_cap_cap_proto = out.File
	file_cap_cap_proto_rawDesc = nil
	file_cap_cap_proto_goTypes = nil
	file_cap_cap_proto_depIdxs = nil
}
